# Generated by Django 5.0.6 on 2024-05-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.ImageField(upload_to='static/certifications/'),
        ),
    ]
