# Generated by Django 5.0.6 on 2024-05-18 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_userprofile_social_media_links_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('index', models.IntegerField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(choices=[('software', 'Software'), ('network', 'Network'), ('cybersecurity', 'Cybersecurity'), ('other', 'Other')], default='software', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
