# Generated by Django 5.0.6 on 2024-05-19 00:19

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='image',
            field=models.ImageField(upload_to=main.models.certification_image_upload_to),
        ),
    ]
