# Generated by Django 5.0.6 on 2024-05-19 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_certification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='does_not_expire',
            field=models.BooleanField(default=False),
        ),
    ]
