# Generated by Django 5.0.6 on 2024-05-19 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_experience_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='project',
            field=models.ForeignKey(blank=True, default='IT', on_delete=django.db.models.deletion.CASCADE, to='main.project'),
        ),
    ]
