# Generated by Django 5.0.6 on 2024-05-19 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_experience_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='user_profile',
        ),
    ]
