# Generated by Django 5.0.6 on 2024-05-19 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_experience_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='abbr',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='education',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
