# Generated by Django 5.0.6 on 2024-05-19 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_category_programminglanguage_remove_skill_image_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Framework_Tools_Category',
        ),
    ]
