# Generated by Django 5.0.6 on 2024-05-19 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_rename_category_framework_tools_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frameworkandtool',
            name='official_website',
        ),
    ]
