# Generated by Django 5.0.6 on 2024-05-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_frameworkandtool_official_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='frameworkandtool',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/framework_tools/'),
        ),
    ]
