# Generated by Django 5.0.6 on 2024-05-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_frameworkandtool_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='frameworks_and_tools',
            field=models.ManyToManyField(related_name='projects', to='main.frameworkandtool'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(related_name='projects', to='main.skill'),
        ),
    ]
