# Generated by Django 5.0.6 on 2024-05-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_project_frameworks_and_tools_project_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='skills',
        ),
        migrations.AddField(
            model_name='project',
            name='programmin_languages',
            field=models.ManyToManyField(related_name='projects', to='main.programminglanguage'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/projects/'),
        ),
    ]
